Repository entando-k8s/entando-component-manager, pull requests merged in 2020-07, with the labels that each got.

#39 ENG-412 fix database migration
  .gitignore
  src/main/resources/application-dev.properties
  src/main/resources/db/changelog/changes/20190809112455-create-schema.yaml
  src/main/resources/db/changelog/changes/20200703113600-update-schema.yaml
  src/main/resources/db/changelog/db.changelog-master.yaml
Labels: approved, size/L

#40 ENG-412 add a 'rename' changeSet
  src/main/java/org/entando/kubernetes/config/AppConfiguration.java
  src/main/java/org/entando/kubernetes/model/bundle/downloader/BundleDownloader.java
  src/main/java/org/entando/kubernetes/model/bundle/downloader/BundleDownloaderFactory.java
  src/main/java/org/entando/kubernetes/model/job/JobStatus.java
  src/main/java/org/entando/kubernetes/model/job/JobType.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleInstallService.java
  src/main/resources/db/changelog/changes/20200703113600-update-schema.yaml
  src/test/java/org/entando/kubernetes/client/model/bundle/EntandoBundleDownloaderTest.java
  src/test/java/org/entando/kubernetes/config/TestAppConfiguration.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
  src/test/java/org/entando/kubernetes/service/EntandoBundleJobServiceTest.java
Labels: approved, size/L

#41 ENG-346 removes support for properties in default widget
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/ComponentSpecDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/DefaultWidgetDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/ContentTemplateProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/PageTemplateProcessor.java
  src/main/java/org/entando/kubernetes/model/entandocore/EntandoCoreFrameDefaultWidget.java
  src/test/java/org/entando/kubernetes/client/model/bundle/processor/PageTemplateProcessorTest.java
  src/test/java/org/entando/kubernetes/client/model/entandocore/EntandoCorePageTemplateTest.java
Labels: approved, size/M

#42 ENG-845 fix casing inconsistencies for label filtering
  src/main/java/org/entando/kubernetes/model/digitalexchange/ComponentType.java
  src/test/java/org/entando/kubernetes/service/digitalexchange/EntandoBundleServiceTest.java
Labels: approved, size/S

#44 ENG-852 added page processor flag on bundle descriptor
  src/main/java/org/entando/kubernetes/config/AppConfiguration.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/PageProcessor.java
  src/main/java/org/entando/kubernetes/model/entandocore/EntandoCoreFrameDefaultWidget.java
  src/main/resources/application.properties
  src/test/java/org/entando/kubernetes/client/model/bundle/processor/PageProcessorTest.java
  src/test/java/org/entando/kubernetes/config/AppConfigurationTest.java
  src/test/java/org/entando/kubernetes/config/TestAppConfiguration.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/DisableProcessorsIntegrationTest.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
  src/test/java/org/entando/kubernetes/utils/TestInstallUtils.java
  src/test/resources/application.properties
  src/test/resources/bundle.tgz
Labels: approved, size/XXL

#46 ENG-880 entando_bundle_component_jobs table and fields to lowercase
  src/main/resources/db/changelog/changes/20200703113600-update-schema.yaml
Labels: approved, size/M

#47 ENG-816 changed install api contract
  pom.xml
  src/main/java/org/entando/kubernetes/controller/digitalexchange/job/EntandoBundleOperationResource.java
  src/main/java/org/entando/kubernetes/controller/digitalexchange/job/EntandoBundleOperationResourceController.java
  src/main/java/org/entando/kubernetes/controller/digitalexchange/job/model/InstallRequest.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/BundleUtilities.java
  src/test/java/org/entando/kubernetes/service/EntandoBundleUtilitiesTest.java
Labels: approved, size/M

#48 ENG-816 list bundles versions
  src/main/java/org/entando/kubernetes/controller/digitalexchange/component/EntandoBundleResource.java
  src/main/java/org/entando/kubernetes/controller/digitalexchange/component/EntandoBundleResourceController.java
  src/main/java/org/entando/kubernetes/controller/digitalexchange/job/EntandoBundleJobResource.java
  src/main/java/org/entando/kubernetes/controller/digitalexchange/job/EntandoBundleJobResourceController.java
  src/main/java/org/entando/kubernetes/controller/digitalexchange/job/EntandoBundleOperationResource.java
  src/main/java/org/entando/kubernetes/controller/digitalexchange/job/EntandoBundleOperationResourceController.java
  src/main/java/org/entando/kubernetes/model/bundle/EntandoBundle.java
  src/main/java/org/entando/kubernetes/model/bundle/EntandoBundleComponentJob.java
  src/main/java/org/entando/kubernetes/model/bundle/EntandoBundleJob.java
  src/main/java/org/entando/kubernetes/model/bundle/EntandoBundleVersion.java
  src/main/java/org/entando/kubernetes/model/bundle/installable/Installable.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/ComponentProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/ContentTemplateProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/ContentTypeProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/DirectoryProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/FileProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/FragmentProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/LabelProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/PageProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/PageTemplateProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/PluginProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/WidgetProcessor.java
  src/main/java/org/entando/kubernetes/model/digitalexchange/EntandoBundleEntity.java
  src/main/java/org/entando/kubernetes/model/job/EntandoBundleComponentJobEntity.java
  src/main/java/org/entando/kubernetes/model/job/EntandoBundleJobDto.java
  src/main/java/org/entando/kubernetes/model/job/EntandoBundleJobEntity.java
  src/main/java/org/entando/kubernetes/model/job/JobScheduler.java
  src/main/java/org/entando/kubernetes/repository/EntandoBundleComponentJobRepository.java
  src/main/java/org/entando/kubernetes/repository/EntandoBundleJobRepository.java
  src/main/java/org/entando/kubernetes/repository/InstalledEntandoBundleRepository.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/BundleUtilities.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/component/EntandoBundleListProcessor.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/component/EntandoBundleService.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/component/EntandoBundleServiceImpl.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleInstallService.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleJobListProcessor.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleJobService.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleUninstallService.java
  src/test/java/org/entando/kubernetes/TestEntitiesGenerator.java
  src/test/java/org/entando/kubernetes/client/model/bundle/EntandoBundleReaderTest.java
  src/test/java/org/entando/kubernetes/client/model/bundle/processor/ContentTypeProcessorTest.java
  src/test/java/org/entando/kubernetes/client/model/bundle/processor/DirectoryProcessorTest.java
  src/test/java/org/entando/kubernetes/client/model/bundle/processor/FileProcessorTest.java
  src/test/java/org/entando/kubernetes/client/model/bundle/processor/LabelProcessorTest.java
  src/test/java/org/entando/kubernetes/client/model/bundle/processor/PageProcessorTest.java
  src/test/java/org/entando/kubernetes/client/model/bundle/processor/PageTemplateProcessorTest.java
  src/test/java/org/entando/kubernetes/config/AppConfigurationTest.java
  src/test/java/org/entando/kubernetes/controller/EntandoBundleControllerTest.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/EntandoBundleApiTest.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/EntandoBundleJobControllerTest.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
  src/test/java/org/entando/kubernetes/service/EntandoBundleJobServiceTest.java
  src/test/java/org/entando/kubernetes/service/digitalexchange/EntandoBundleServiceTest.java
  src/test/java/org/entando/kubernetes/utils/TestInstallUtils.java
Labels: approved, size/XXL

#49 Eng 415 manual component bundle deletion
  src/main/java/org/entando/kubernetes/client/core/DefaultEntandoCoreClient.java
  src/test/java/org/entando/kubernetes/client/EntandoCoreClientTest.java
  src/test/java/org/entando/kubernetes/utils/EntandoCoreMockServer.java
  src/test/java/org/entando/kubernetes/utils/EntandoGenericMockServer.java
Labels: approved, size/L

#50 Eng 952 filter by id name version not working as expected
  pom.xml
  src/main/java/org/entando/kubernetes/service/digitalexchange/component/EntandoBundleListProcessor.java
  src/test/java/org/entando/kubernetes/config/AppConfigurationTest.java
  src/test/java/org/entando/kubernetes/service/digitalexchange/EntandoBundleServiceTest.java
Labels: approved, size/S

#52 ENG-960 changed how to retrieve bundle versions
  src/main/java/org/entando/kubernetes/model/bundle/EntandoBundleVersion.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/component/EntandoBundleServiceImpl.java
  src/test/java/org/entando/kubernetes/service/digitalexchange/EntandoBundleServiceTest.java
Labels: approved, size/S

#51 ENG-958 ecr presents wrong latest bundle version
  pom.xml
  src/main/java/org/entando/kubernetes/model/bundle/EntandoBundle.java
  src/main/java/org/entando/kubernetes/model/bundle/EntandoBundleVersion.java
  src/test/java/org/entando/kubernetes/model/bundle/EntandoBundleTest.java
  src/test/resources/payloads/k8s-svc/bundles/bundle_with_versions.json
Labels: approved, size/L
