Repository entando-k8s/entando-component-manager, pull requests merged in 2020-06, with the labels that each got.

#30 ENG-562 included H2 database dependency
  pom.xml
Labels: size/XS

#32 ENG-647 updates response status to 201
  OWNERS
  src/main/java/org/entando/kubernetes/controller/digitalexchange/job/EntandoBundleJobResource.java
  src/main/java/org/entando/kubernetes/controller/digitalexchange/job/EntandoBundleJobResourceController.java
  src/main/java/org/entando/kubernetes/controller/digitalexchange/job/EntandoBundleOperationResource.java
  src/main/java/org/entando/kubernetes/controller/digitalexchange/job/EntandoBundleOperationResourceController.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
Labels: approved, size/L

#29 Add ENTANDO_BUNDLE_TYPE to the README.
  README.md
Labels: approved, size/M

#33 Fix cors
  OWNERS
  config/owasp-dependency-check-suppression.xml
  pom.xml
  src/main/java/org/entando/kubernetes/EntandoKubernetesJavaApplication.java
  src/main/java/org/entando/kubernetes/config/CorsAccessControlConfiguration.java
  src/main/java/org/entando/kubernetes/config/CorsConfiguration.java
  src/main/java/org/entando/kubernetes/config/SecurityConfiguration.java
  src/main/java/org/entando/kubernetes/model/digitalexchange/EntandoBundleJob.java
  src/main/resources/application-dev.properties
Labels: approved, size/L

#36 ENG-535 Added support for bundles with complex content types
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/ContentTypeAttribute.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/ContentTypeDescriptor.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleInstallService.java
  src/test/java/org/entando/kubernetes/client/model/bundle/processor/ContentTypeProcessorTest.java
  src/test/java/org/entando/kubernetes/utils/FileUtils.java
  src/test/resources/bundle.tgz
  src/test/resources/bundle/contenttypes/my_content_type_descriptor.yaml
Labels: approved, size/L
