Repository entando-k8s/entando-component-manager, pull requests merged in 2020-09, with the labels that each got.

#55 Updates the pom to use the new 6.2.x base version
  pom.xml
Labels: approved, size/XS

#56 ENG-1121 commented out bundle's page configuration system
  src/main/java/org/entando/kubernetes/config/AppConfiguration.java
  src/main/resources/application.properties
  src/test/java/org/entando/kubernetes/config/AppConfigurationTest.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/DisableProcessorsIntegrationTest.java
Labels: approved, lgtm, size/M

#57 Eng 693 progress not updated
  pom.xml
  src/main/java/org/entando/kubernetes/controller/digitalexchange/job/EntandoBundleOperationResourceController.java
  src/main/java/org/entando/kubernetes/model/bundle/EntandoBundle.java
  src/main/java/org/entando/kubernetes/model/bundle/EntandoBundleJob.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/ComponentProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/ContentTemplateProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/ContentTypeProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/DirectoryProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/FileProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/FragmentProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/LabelProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/PageProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/PageTemplateProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/PluginProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/WidgetProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/reader/BundleReader.java
  src/main/java/org/entando/kubernetes/model/digitalexchange/ComponentType.java
  src/main/java/org/entando/kubernetes/model/job/EntandoBundleComponentJobEntity.java
  src/main/java/org/entando/kubernetes/model/job/EntandoBundleJobEntity.java
  src/main/java/org/entando/kubernetes/model/job/HasInstallable.java
  src/main/java/org/entando/kubernetes/model/job/HasProgress.java
  src/main/java/org/entando/kubernetes/model/job/JobProgress.java
  src/main/java/org/entando/kubernetes/model/job/JobResult.java
  src/main/java/org/entando/kubernetes/model/job/JobScheduler.java
  src/main/java/org/entando/kubernetes/model/job/JobTracker.java
  src/main/java/org/entando/kubernetes/model/job/TrackableJob.java
  src/main/java/org/entando/kubernetes/repository/EntandoBundleComponentJobRepository.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleInstallService.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleJobService.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleUninstallService.java
  src/test/java/org/entando/kubernetes/client/EntandoBundleComponentJobRepositoryTestDouble.java
  src/test/java/org/entando/kubernetes/client/EntandoBundleJobRepositoryTestDouble.java
  src/test/java/org/entando/kubernetes/client/EntandoCoreClientTest.java
  src/test/java/org/entando/kubernetes/client/K8SServiceClientTest.java
  src/test/java/org/entando/kubernetes/client/model/bundle/EntandoBundleDownloaderTest.java
  src/test/java/org/entando/kubernetes/client/model/bundle/EntandoBundleReaderTest.java
  src/test/java/org/entando/kubernetes/client/model/bundle/processor/ContentTypeProcessorTest.java
  src/test/java/org/entando/kubernetes/client/model/bundle/processor/DirectoryProcessorTest.java
  src/test/java/org/entando/kubernetes/client/model/bundle/processor/FileProcessorTest.java
  src/test/java/org/entando/kubernetes/client/model/bundle/processor/LabelProcessorTest.java
  src/test/java/org/entando/kubernetes/client/model/bundle/processor/PageProcessorTest.java
  src/test/java/org/entando/kubernetes/client/model/bundle/processor/PageTemplateProcessorTest.java
  src/test/java/org/entando/kubernetes/client/model/entandocore/EntandoCorePageTemplateTest.java
  src/test/java/org/entando/kubernetes/controller/EntandoBundleControllerTest.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/DisableProcessorsIntegrationTest.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
  src/test/java/org/entando/kubernetes/model/bundle/EntandoBundleTest.java
  src/test/java/org/entando/kubernetes/service/EntandoBundleJobServiceTest.java
  src/test/java/org/entando/kubernetes/service/InstallServiceTest.java
  src/test/java/org/entando/kubernetes/service/digitalexchange/EntandoBundleServiceTest.java
  src/test/java/org/entando/kubernetes/utils/EntandoCoreMockServer.java
  src/test/java/org/entando/kubernetes/utils/EntandoGenericMockServer.java
  src/test/java/org/entando/kubernetes/utils/TestInstallUtils.java
Labels: approved, size/XXL

#59 Eng 1125 add ability to install groups
  src/main/java/org/entando/kubernetes/client/core/DefaultEntandoCoreClient.java
  src/main/java/org/entando/kubernetes/client/core/EntandoCoreClient.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/ComponentSpecDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/GroupDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/installable/GroupInstallable.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/GroupProcessor.java
  src/main/java/org/entando/kubernetes/model/digitalexchange/ComponentType.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/component/EntandoBundleComponentUsageService.java
  src/test/java/org/entando/kubernetes/config/AppConfigurationTest.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
  src/test/java/org/entando/kubernetes/model/bundle/EntandoBundleReaderTest.java
  src/test/java/org/entando/kubernetes/utils/TestInstallUtils.java
  src/test/resources/README.md
  src/test/resources/bundle.tgz
  src/test/resources/bundle/descriptor.yaml
  src/test/resources/bundle/groups/my-group.yaml
Labels: approved, size/L

#61 ENG-1128 accept a list of categories and groups as descriptors
  pom.xml
  src/main/java/org/entando/kubernetes/model/bundle/processor/CategoryProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/GroupProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/reader/BundleReader.java
  src/test/java/org/entando/kubernetes/model/bundle/EntandoBundleReaderTest.java
  src/test/resources/bundle.tgz
  src/test/resources/bundle/categories/my-category.yaml
  src/test/resources/bundle/groups/my-group.yaml
Labels: approved, size/M

#62 Eng 1288 moves labels into dedicated files
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/ComponentSpecDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/LabelProcessor.java
  src/test/java/org/entando/kubernetes/model/bundle/EntandoBundleReaderTest.java
  src/test/java/org/entando/kubernetes/model/bundle/processor/LabelProcessorTest.java
  src/test/resources/bundle/descriptor.yaml
  src/test/resources/bundle/labels/labels.yaml
Labels: approved, size/M

#63 ENG-1294 makes the delete of core components resilient to 404 errors
  src/main/java/org/entando/kubernetes/client/core/DefaultEntandoCoreClient.java
  src/test/java/org/entando/kubernetes/client/EntandoCoreClientTest.java
Labels: approved, size/M
