Repository entando-k8s/entando-component-manager, pull requests merged in 2020-10, with the labels that each got.

#64 ENG-1291 languages support
  src/main/java/org/entando/kubernetes/client/core/DefaultEntandoCoreClient.java
  src/main/java/org/entando/kubernetes/client/core/EntandoCoreClient.java
  src/main/java/org/entando/kubernetes/model/bundle/ComponentType.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/ComponentSpecDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/LanguageDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/installable/LanguageInstallable.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/LanguageProcessor.java
  src/main/java/org/entando/kubernetes/model/entandocore/EntandoCoreLanguage.java
  src/test/java/org/entando/kubernetes/client/model/entandocore/EntandoCoreLanguageTest.java
  src/test/java/org/entando/kubernetes/config/AppConfigurationTest.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
  src/test/java/org/entando/kubernetes/model/bundle/EntandoBundleReaderTest.java
  src/test/java/org/entando/kubernetes/model/bundle/processor/LanguageProcessorTest.java
  src/test/resources/bundle/descriptor.yaml
  src/test/resources/bundle/languages/languages.yaml
Labels: approved, size/L

#65 ENG-1123 Added support for installing pages with widgets
  .gitignore
  src/main/java/org/entando/kubernetes/client/core/DefaultEntandoCoreClient.java
  src/main/java/org/entando/kubernetes/client/core/EntandoCoreClient.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/PageDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/PluginDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/WidgetConfigurationDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/installable/PageInstallable.java
  src/main/java/org/entando/kubernetes/model/entandocore/EntandoCorePageWidgetConfiguration.java
  src/test/java/org/entando/kubernetes/client/model/entandocore/EntandoCorePageTest.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
  src/test/java/org/entando/kubernetes/model/bundle/EntandoBundleReaderTest.java
  src/test/java/org/entando/kubernetes/model/bundle/processor/PageProcessorTest.java
  src/test/resources/bundle/pages/my_page_descriptor.yaml
Labels: approved, size/L

#66 Eng 1266 tweaks for ssh support
  Dockerfile
  entrypoint.sh
  jenkins-x.yml
  passwd.template
  pom.xml
  src/main/java/org/entando/kubernetes/model/bundle/downloader/GitBundleDownloader.java
  src/test/java/org/entando/kubernetes/model/bundle/EntandoBundleDownloaderTest.java
Labels: approved, size/M

#67 ENG-1364 updated content type attribute descriptor with latest changes on core
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/ContentTypeAttribute.java
  src/test/resources/bundle/contenttypes/my_content_type_descriptor.yaml
Labels: approved, size/S

#68 ENG-1370 support for both old and new plugin descriptor format - QUIC…
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/BundleDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/PluginDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/plugin/PluginDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/plugin/PluginDescriptorV1Metadata.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/plugin/PluginDescriptorV1Role.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/plugin/PluginDescriptorV1Spec.java
  src/main/java/org/entando/kubernetes/model/bundle/installable/PluginInstallable.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/PluginProcessor.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/BundleUtilities.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
  src/test/java/org/entando/kubernetes/model/bundle/EntandoBundleReaderTest.java
  src/test/java/org/entando/kubernetes/model/bundle/EntandoBundleTest.java
  src/test/java/org/entando/kubernetes/model/bundle/PluginDescriptorConvertionTest.java
  src/test/java/org/entando/kubernetes/service/EntandoBundleUtilitiesTest.java
  src/test/java/org/entando/kubernetes/utils/TestInstallUtils.java
  src/test/resources/bundle.tgz
  src/test/resources/bundle/descriptor.yaml
  src/test/resources/bundle/plugins/todomvcV1.yaml
  src/test/resources/bundle/plugins/todomvcV2.yaml
Labels: approved, size/XL

#69 ENG-1380 plugin image max length error update
  src/main/java/org/entando/kubernetes/service/digitalexchange/BundleUtilities.java
Labels: approved, size/XS

#70 Eng 1380 plugin uninstallation fix
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/ContentTypeDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/installable/PluginInstallable.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/PluginProcessor.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
  src/test/resources/bundle/descriptor.yaml
  src/test/resources/bundle/plugins/todomvcV2_withDeploymentBasePath.yaml
Labels: approved, size/M

#71 Eng 1359 permission and ingresspath plugin descriptor
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/plugin/PluginDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/plugin/PluginPermission.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/BundleUtilities.java
  src/test/java/org/entando/kubernetes/model/bundle/EntandoBundleReaderTest.java
  src/test/java/org/entando/kubernetes/service/EntandoBundleUtilitiesTest.java
  src/test/resources/bundle.tgz
  src/test/resources/bundle/descriptor.yaml
  src/test/resources/bundle/plugins/todomvcV2_complete.yaml
  src/test/resources/bundle/plugins/todomvcV2_withDeploymentBasePath.yaml
Labels: approved, size/L

#73 ENG-1422: migrate the component-manager to java11
  Dockerfile
  pom.xml
Labels: approved, size/XS

#74 Updating OWNERS file
  OWNERS
  OWNERS_ALIASES
Labels: approved, size/S

#76 javadoc-fix changed @class to @link and fixed linked path
  src/main/java/org/entando/kubernetes/model/bundle/processor/ComponentProcessor.java
Labels: approved, size/XS

#77 ENG-1422: Remove java execution option UseCGroupMemoryLimitForHeap as…
  Dockerfile
Labels: approved, size/XS
