Repository entando-k8s/entando-component-manager, pull requests merged in 2021-02, with the labels that each got.

#96 ENG-1757 plugin securityLevel management
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/plugin/PluginDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/plugin/PluginDescriptorV1Spec.java
  src/main/java/org/entando/kubernetes/model/bundle/processor/PluginProcessor.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/BundleUtilities.java
  src/test/java/org/entando/kubernetes/model/bundle/processor/PluginProcessorTest.java
  src/test/java/org/entando/kubernetes/service/EntandoBundleUtilitiesTest.java
  src/test/java/org/entando/kubernetes/service/InstallServiceTest.java
  src/test/java/org/entando/kubernetes/stubhelper/PluginStubHelper.java
  src/test/resources/bundle/plugins/todomvcV2_complete.yaml
Labels: approved, lgtm, size/L

#97 ENG-1711 paramerized VERSION in Docker and upgraded custom-model
  Dockerfile
  jenkins-x.yml
  pom.xml
  skaffold.yaml
  src/main/java/org/entando/kubernetes/client/k8ssvc/DefaultK8SServiceClient.java
  src/test/java/org/entando/kubernetes/client/K8SServiceClientTest.java
  src/test/java/org/entando/kubernetes/client/K8SServiceClientTestDouble.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/DisableProcessorsIntegrationTest.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/UpdateFlowTest.java
  src/test/java/org/entando/kubernetes/service/KubernetesServiceTest.java
  src/test/java/org/entando/kubernetes/utils/TestInstallUtils.java
Labels: approved, size/M

#98 ENG-1754 on uninstallation with conflict strategy not equal to "OVERR…
  src/main/java/org/entando/kubernetes/client/core/DefaultEntandoCoreClient.java
  src/main/java/org/entando/kubernetes/client/core/EntandoCoreClient.java
  src/main/java/org/entando/kubernetes/model/bundle/installable/PageConfigurationInstallable.java
  src/main/java/org/entando/kubernetes/model/bundle/installable/PageInstallable.java
  src/test/java/org/entando/kubernetes/client/EntandoCoreClientTestDouble.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/UpdateFlowTest.java
  src/test/java/org/entando/kubernetes/model/bundle/installable/PageInstallableTest.java
Labels: approved, lgtm, size/M

#99 ENG-1888 changed TEXT to VARCHAR
  src/main/resources/db/changelog/changes/20190809112455-create-schema.yaml
  src/main/resources/db/changelog/changes/20201105193500-update-schema.yaml
Labels: approved, size/XS

#101 ENG-1894 UUID management in MySQL db
  src/main/java/org/entando/kubernetes/model/job/EntandoBundleComponentJobEntity.java
  src/main/java/org/entando/kubernetes/model/job/EntandoBundleJobEntity.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleInstallService.java
  src/test/java/org/entando/kubernetes/service/InstallServiceTest.java
Labels: approved, size/M

#102 ENG-1869 bundle-type property read management (read from k8s-service,…
  src/main/java/org/entando/kubernetes/model/bundle/BundleType.java
  src/main/java/org/entando/kubernetes/model/bundle/EntandoBundle.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/BundleDescriptor.java
  src/main/java/org/entando/kubernetes/model/job/EntandoBundleEntity.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/BundleUtilities.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/component/EntandoBundleServiceImpl.java
  src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleInstallService.java
  src/main/resources/db/changelog/changes/20210224124500-bundle-type-column.yaml
  src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
  src/test/java/org/entando/kubernetes/model/bundle/processor/ContentTypeProcessorTest.java
  src/test/java/org/entando/kubernetes/model/bundle/processor/LabelProcessorTest.java
  src/test/java/org/entando/kubernetes/model/bundle/processor/LanguageProcessorTest.java
  src/test/java/org/entando/kubernetes/model/bundle/processor/PageConfigurationProcessorTest.java
  src/test/java/org/entando/kubernetes/model/bundle/processor/PageProcessorTest.java
  src/test/java/org/entando/kubernetes/model/bundle/processor/PageTemplateProcessorTest.java
  src/test/java/org/entando/kubernetes/model/bundle/processor/PluginProcessorTest.java
  src/test/java/org/entando/kubernetes/service/EntandoBundleUtilitiesTest.java
  src/test/java/org/entando/kubernetes/stubhelper/BundleStubHelper.java
Labels: approved, size/L
