Repository entando-k8s/entando-component-manager, pull requests merged in 2021-01, with the labels that each got.

#91 ENG-1616 listModel, defaultModel, viewPage content fields management
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/PageTemplateConfigurationDescriptor.java
  src/main/java/org/entando/kubernetes/model/bundle/descriptor/content/ContentDescriptor.java
  src/main/java/org/entando/kubernetes/model/entandocore/EntandoCorePageTemplateConfiguration.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/UpdateFlowTest.java
  src/test/resources/bundle/contents/cng102-descriptor.yaml
Labels: approved, size/S

#92 ENG-1670 uninstallation to delete AppPluginLink CR
  src/main/java/org/entando/kubernetes/model/bundle/installable/PluginInstallable.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
  src/test/java/org/entando/kubernetes/model/bundle/processor/PluginProcessorTest.java
  src/test/java/org/entando/kubernetes/utils/TestInstallUtils.java
Labels: approved, size/S

#93 ENG-1727 fixed issue with assets directory location
  src/main/java/org/entando/kubernetes/model/bundle/processor/AssetProcessor.java
  src/main/java/org/entando/kubernetes/model/bundle/reader/BundleReader.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
  src/test/java/org/entando/kubernetes/controller/mockmvc/UpdateFlowTest.java
  src/test/java/org/entando/kubernetes/utils/TestInstallUtils.java
  src/test/resources/bundle.tgz
  src/test/resources/bundle/assets/anotherasset/another_image.jpg
  src/test/resources/bundle/assets/anotherasset/anotherasset.yaml
  src/test/resources/bundle/descriptor.yaml
Labels: approved, size/S

#95 IV-1755 Fixing git clone on Windows
  src/main/java/org/entando/kubernetes/model/bundle/downloader/GitBundleDownloader.java
Labels: approved, lgtm, size/S

#94 ENG-1711 updated to rhel UBI
  Dockerfile
  pom.xml
Labels: approved, lgtm, size/M
